[package]
name = "PyFront_RsBack"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
sqlx = "0.6.2"
surrealdb = "1.0.0-beta.8"
tokio = "1.24.1"
